In [6]:
#오늘의 코딩 테스트 정렬 sorting

def solution(priorities):
    sorted_priorities = sorted(priorities, reverse=True)

    return sorted_priorities

  
print(solution([3, 1, 5, 2, 4]))
print(solution([2, 5, 2, 4, 5]))
print(solution([7]))

[5, 4, 3, 2, 1]
[5, 5, 4, 2, 2]
[7]

In [12]:
# join(): 인덱스 기반 결합
# pandas의 join은 반드시 인덱스가 있어야 함
# join() merge() 차이점: 둘 다 두 개의 dataframe을 합치는 것인데, 어떤 기준으로 합치느냐가 핵심 차이
# join은 인덱스를 기준으로 합치는 데 편함
# merge는 특정 컬럼을 기준으로 합치는데 편함

# 연습문제 8.
# 가장 먼저 해야 하는 것 csv 파일 읽어오기


import pandas as pd
customer_master = pd.read_csv(
    './customer_master.csv'
)
customer_order_summary = pd.read_csv(
    './customer_order_summary.csv'
)

# join을 사용해서 두 개의 데이터프레임을 결합 > 인덱스 필요
customer_master_idx = customer_master.set_index('customer_id')
customer_order_summary_idx = customer_order_summary.set_index('customer_id')

df_customer_view = customer_master_idx.join(  # 고객 마스터의 데이터가 모두 유지되도록 left join
    customer_order_summary_idx,
    how='left'
)

df_customer_view.head()

,signup_date,region,membership_tier,marketing_opt_in,total_orders,total_spent,avg_order_value,last_order_date
customer_id,,,,,,,,
244220c6-4b0c-400c-a626-c97d73fe6a93,2023-03-01,Africa,Gold,Y,1.0,447.84,447.84,2023-05-02
3e773705-cb10-4e5b-bb0c-85e2a9bb8ea1,2022-10-27,Oceania,Gold,Y,1.0,402.78,402.78,2023-03-07
66815708-05fb-4b20-ad31-5ef756500854,2021-01-19,Europe,Bronze,Y,1.0,637.95,637.95,2023-01-05
d44b52d4-a5f3-40c9-b783-ee09638be0f6,2021-08-21,Oceania,Gold,N,1.0,217.36,217.36,2023-04-15
6b40431b-cd24-407e-b8df-bd843c1a55f3,2024-10-15,Oceania,Bronze,N,1.0,941.42,941.42,2025-03-24

In [15]:
# groupby & pivot_table
import pandas as pd
df = pd.read_csv('./ecommerce_orders_online.csv')
df.groupby("product_category")['revenue'].sum()
print(df.groupby("product_category")['revenue'].sum())

df.groupby("product_category")['revenue'].count()
print(df.groupby("product_category")['revenue'].count())

product_category
Automotive     273283.55
Beauty         259016.59
Electronics    254451.65
Fashion        264342.19
Home           267710.71
Sports         270807.50
Toys           273722.10
Name: revenue, dtype: float64
product_category
Automotive     370
Beauty         353
Electronics    356
Fashion        366
Home           354
Sports         330
Toys           349
Name: revenue, dtype: int64

In [17]:
import pandas as pd
df = pd.read_csv('./ecommerce_orders_online.csv')
total_amount = (df.groupby("payment_method")["quantity"].sum().reset_index)

avg_quantity = (df.groupby("payment_method")["quantity"].mean().reset_index)

print(total_amount)
print(avg_quantity)

<bound method Series.reset_index of payment_method
BankTransfer    2022
Cash            1833
CreditCard      1916
PayPal          2039
Name: quantity, dtype: int64>
<bound method Series.reset_index of payment_method
BankTransfer    3.110769
Cash            3.160345
CreditCard      3.198664
PayPal          3.127301
Name: quantity, dtype: float64>

In [18]:
import pandas as pd

customer_master = pd.read_csv('./customer_master.csv')
customer_order_summary = pd.read_csv('./customer_order_summary.csv')

df_customer = pd.merge(
    customer_master,
    customer_order_summary,
    on='customer_id',
    how='inner'
)

total_spent = (
    df_customer.groupby('membership_tier')['total_spent']
    .sum()
    .reset_index()
)

avg_spent = (
    df_customer.groupby('membership_tier')['total_spent']
    .mean()
    .reset_index()
)

print(total_spent)
print(avg_spent)

  membership_tier  total_spent
0          Bronze   1596576.22
1            Gold    656314.76
2        Platinum    180174.57
3          Silver   1113429.96
  membership_tier  total_spent
0          Bronze   735.071924
1            Gold   739.926449
2        Platinum   790.239342
3          Silver   735.908764

In [19]:
# agg(): 다중 집계 함수 적용
# agg 안에는 들어가는 여러 항복들은 다음과 같이 구성. 칼럼명 = ('기준칼럼','집계 방벙')

In [22]:
import pandas as pd

df = pd.read_csv('./ecommerce_orders_online.csv')
region_summary = df.groupby("region").agg(total_sales= ("revenue","sum"),
 avg_sales = ("revenue","mean"),order_count = ("order_id","count"))

region_summary

               total_sales   avg_sales  order_count
region
Africa           318321.44  768.892367          415
Asia             352406.88  802.749157          441
Europe           277171.11  707.069158          392
North America    292170.00  741.548223          395
Oceania          304877.46  725.898714          420
South America    316329.04  749.594882          424

In [25]:
import pandas as pd
df = pd.read_csv('./ecommerce_orders_online.csv')
category_summary = df.groupby("product_category").agg(
    total_revenue = ("revenue","sum"), total_quantity = ("quantity","sum"),
    order_count = ("order_id","count")
).reset_index()

category_summary

  product_category  total_revenue  total_quantity  order_count
0       Automotive      273283.55            1133          372
1           Beauty      259016.59            1134          353
2      Electronics      254451.65            1091          357
3          Fashion      264342.19            1156          367
4             Home      267710.71            1129          355
5           Sports      270807.50            1084          331
6             Toys      273722.10            1085          349

In [39]:
import pandas as pd

customer_master = pd.read_csv('./customer_master.csv')
customer_order_summary = pd.read_csv('./customer_order_summary.csv')


df_customer = pd.merge(customer_master, customer_order_summary, 
on ='customer_id', how = 'inner')


tier_summary = df_customer.groupby("membership_tier").agg(
    total_sales =("total_spent","sum"), avg_spent = ("total_spent","mean"),
    customer_count = ("customer_id", "count")
).reset_index

tier_summary

<bound method DataFrame.reset_index of                  total_sales   avg_spent  customer_count
membership_tier
Bronze            1596576.22  735.071924            2172
Gold               656314.76  739.926449             887
Platinum           180174.57  790.239342             228
Silver            1113429.96  735.908764            1513>

In [41]:
# pivot_table(): 데이터 재구성 요약

pivot = pd.pivot_table(
    df, index='region', columns='product_category', values='revenue' ,aggfunc= 'sum',
    fill_value=0
)
pivot

product_category,Automotive,Beauty,Electronics,Fashion,Home,Sports,Toys
region,,,,,,,
Africa,55086.77,42478.75,39539.35,36371.12,46148.89,49103.73,49295.64
Asia,40928.23,63110.85,48996.14,48359.97,48701.56,57052.87,45091.67
Europe,39819.43,33040.37,29382.71,47248.31,42049.60,48532.46,33143.51
North America,47493.43,36611.96,29728.69,39389.38,46748.63,43892.39,47840.22
Oceania,36755.08,38928.21,45101.74,42320.67,40538.12,44766.29,55579.92
South America,51718.37,44846.45,61633.84,49056.47,38477.75,27459.76,39884.00

In [45]:
import pandas as pd
df = pd.read_csv('./ecommerce_orders_online.csv')

pivot = pd.pivot_table(
    df, index='region', columns='payment_method', values='revenue', aggfunc='sum',
    fill_value=0
)
pivot

payment_method  BankTransfer      Cash  CreditCard    PayPal
region
Africa              89622.13  69823.02    80127.72  75075.54
Asia                91539.87  73851.48    92638.96  91646.06
Europe              64014.32  79168.89    66030.68  67017.82
North America       75024.63  63485.37    74191.15  78239.95
Oceania             88483.15  66764.31    72901.12  75996.96
South America       77982.80  67173.65    74421.61  92718.60

In [50]:
import pandas as pd
df = pd.read_csv('./ecommerce_orders_online.csv')

top10 = df.sort_values('revenue', ascending=False)
top10.head(10)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
177,91553,2023-11-28,3de8de21-11d8-4be1-aeb9-c7a5fb0eb61b,Home,NaN,6,446.103,0.0,PayPal,1.0,4.1,2676.62
900,11969,2023-11-06,fa87fb09-6f26-424b-b740-eaf17e991651,Beauty,Asia,6,432.801,0.0,CreditCard,3.0,2.2,2596.81
1821,86638,2025-11-05,5caea310-7a44-4339-835a-8dc67380ea6c,Fashion,Asia,6,424.710,0.0,PayPal,7.0,3.0,2548.26
2448,88232,2024-11-09,a0ab393c-88c8-4ded-bf6f-8c13453af993,Sports,Europe,6,424.170,0.0,CreditCard,1.0,2.1,2545.02
649,48215,2023-11-25,cc5fcfb8-9fc6-4092-b91c-187a3179ab12,Sports,North America,6,417.915,0.0,PayPal,3.0,3.5,2507.49
643,30865,2025-12-11,c526199b-1591-4a0d-b407-18eacf553bea,Toys,Asia,5,493.280,0.0,Cash,6.0,NaN,2466.40
864,18553,2025-03-19,4fd7fa9e-d44a-4f1d-9f26-808c0a9b3d13,Automotive,Oceania,5,488.270,0.0,CreditCard,8.0,3.1,2441.35
74,68271,2024-02-11,a55bb796-91bc-45f4-b2f7-ac20a4f305f0,Automotive,Europe,5,485.880,0.0,PayPal,3.0,2.0,2429.40
1906,63023,2024-04-25,3cf1b6e7-f1c8-44ec-9486-293e0d2530da,Automotive,Asia,5,483.530,0.0,BankTransfer,7.0,3.1,2417.65
324,31149,2023-12-15,fd854fa2-eb8c-4c85-9b13-5ce8dec8551f,Fashion,Europe,5,483.280,0.0,Cash,1.0,2.7,2416.40

In [ ]:
import pandas as pd
df = pd.read_csv('./ecommerce_orders_online.csv')
df.describe() #describe()사용하면 최대,최소 확인 가능

result = df.sort_values('delivery_days',ascending=False).reset_index(drop=True)
result[['order_id','delivery_days','region']].head(10)

   order_id  delivery_days         region
0     32885            9.0        Oceania
1     76207            9.0         Africa
2     86967            9.0  South America
3     87672            9.0        Oceania
4      2260            9.0         Europe
5      6302            9.0         Europe
6     11090            9.0           Asia
7     85388            9.0  North America
8     98255            9.0         Europe
9     71950            9.0  South America

In [54]:
import pandas as pd
df = pd.read_csv('./ecommerce_orders_online.csv')

result= df.sort_values('customer_rating', ascending=True).reset_index(drop=True)
result[['order_id','product_category','customer_rating']].head(10)

   order_id product_category  customer_rating
0     98190      Electronics              2.0
1     68271       Automotive              2.0
2      3738             Home              2.0
3     91940           Beauty              2.0
4     90299          Fashion              2.0
5     31221       Automotive              2.0
6     27117      Electronics              2.0
7     31121           Sports              2.0
8      1092             Home              2.0
9     48262       Automotive              2.0

In [ ]:
# sort_index()

import pandas as pd
df = pd.read_csv('./ecommerce_orders_online.csv')

region_revenue = df.groupby("region", sort=False)["revenue"].sum() #sort = False ???

print('/n정렬 후 (인덱스 알파벳순):')
print(region_revenue.sort_index())

/n정렬 후 (인덱스 알파벳순):
region
Africa           318321.44
Asia             352406.88
Europe           277171.11
North America    292170.00
Oceania          304877.46
South America    316329.04
Name: revenue, dtype: float64

In [58]:
import pandas as pd
df = pd.read_csv('./ecommerce_orders_online.csv')

category_revenue = df.groupby("product_category",sort=False)["revenue"].sum()


print('정렬 전:')
print(category_revenue)

print('\n정렬 후:')
print(category_revenue.sort_index())

정렬 전:
product_category
Automotive     273283.55
Beauty         259016.59
Fashion        264342.19
Electronics    254451.65
Sports         270807.50
Home           267710.71
Toys           273722.10
Name: revenue, dtype: float64

정렬 후:
product_category
Automotive     273283.55
Beauty         259016.59
Electronics    254451.65
Fashion        264342.19
Home           267710.71
Sports         270807.50
Toys           273722.10
Name: revenue, dtype: float64

In [59]:
import pandas as pd

df = pd.read_csv('./customer_master.csv')

tier_count = df.groupby(
    'membership_tier'
)['customer_id'].count()

print(tier_count.sort_index())

membership_tier
Bronze      2235
Gold         892
Platinum     228
Silver      1545
Name: customer_id, dtype: int64

In [60]:
# lambda 함수
import pandas as pd
df = pd.read_csv('./ecommerce_orders_online.csv')

df['revenue_adjusted'] = df['revenue'].apply(lambda x: x*1.1)

df[['revenue','revenue_adjusted']].head()

   revenue  revenue_adjusted
0   239.36           263.296
1   196.67           216.337
2    88.72            97.592
3   253.76           279.136
4   669.60           736.560

In [61]:
import pandas as pd

df = pd.read_csv('./ecommerce_orders_online.csv')

df['delivery_type'] = df['delivery_days'].apply(
    lambda x: '빠른 배송' if x <= 3 else '일반 배송'
)

df[
    ['delivery_days', 'delivery_type']
].head()

   delivery_days delivery_type
0            1.0         빠른 배송
1            2.0         빠른 배송
2            2.0         빠른 배송
3            9.0         일반 배송
4            3.0         빠른 배송

In [62]:
# split(): 문자열 분리
import pandas as pd

df = pd.read_csv('./ecommerce_orders_online.csv')

df[['month', 'day', 'year']] = df[
    'order_date'
].str.split('-', expand=True)

df[
    ['order_date', 'month', 'day', 'year']
].head()

   order_date month day year
0  2024-08-29  2024  08   29
1  2025-09-30  2025  09   30
2  2023-10-30  2023  10   30
3  2023-09-07  2023  09   07
4  2025-08-16  2025  08   16

In [65]:
from dateutil.rrule import rrule,WEEKLY,MO
from datetime import datetime

promo_dates = list(rrule(WEEKLY, count=5, byweekday=MO, dtstart=(2024,1,1)))

AttributeError: 'tuple' object has no attribute 'toordinal'

In [ ]:
# EDA
# EDA -> 데이터처리-> AI 모델 개발/테스트
# *그런데, AI 모델의 성능이 문제를 해결할 만큼 성능이 안좋음 -> 다시 EDA 작업

In [1]:
import pandas as pd 

df = pd.read_csv('./ecommerce_sales_analytics_5000.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   str
 2   customer_id       4980 non-null   str
 3   product_category  4969 non-null   str
 4   region            4965 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        4974 non-null   float64
 7   discount          4959 non-null   float64
 8   payment_method    4969 non-null   str
 9   delivery_days     4975 non-null   float64
 10  customer_rating   4955 non-null   float64
 11  revenue           4980 non-null   float64
dtypes: float64(5), int64(2), str(5)
memory usage: 468.9 KB

In [2]:
df.describe()

,order_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.00000,5000.000000,4974.000000,4959.000000,4975.000000,4955.000000,4980.000000
mean,49557.64660,3.105600,249.981411,0.048941,5.038392,3.493925,734.090110
std,28846.15789,1.430824,142.720577,0.060582,2.582754,0.873483,571.096263
min,71.00000,1.000000,4.662000,0.000000,1.000000,2.000000,4.540000
25%,24503.25000,2.000000,124.482500,0.000000,3.000000,2.700000,277.167500
50%,49506.00000,3.000000,250.630000,0.000000,5.000000,3.500000,577.795000
75%,74508.50000,4.000000,371.238000,0.100000,7.000000,4.300000,1077.747500
max,99992.00000,6.000000,499.890000,0.200000,9.000000,5.000000,2676.620000

In [3]:
df['product_category'].value_counts()

product_category
Toys           738
Sports         737
Automotive     714
Home           713
Beauty         707
Fashion        684
Electronics    676
Name: count, dtype: int64

In [4]:
df.isna().sum()

order_id             0
order_date           0
customer_id         20
product_category    31
region              35
quantity             0
unit_price          26
discount            41
payment_method      31
delivery_days       25
customer_rating     45
revenue             20
dtype: int64

In [5]:
df.groupby(
    'product_category'
)['revenue'].sum().sort_values(
    ascending=False
)

product_category
Sports         556357.79
Toys           546387.97
Home           533954.71
Automotive     520446.91
Fashion        502964.06
Beauty         490516.64
Electronics    484721.19
Name: revenue, dtype: float64

In [6]:
df.groupby(
    'delivery_days'
)['customer_rating'].mean().round(2)

delivery_days
1.0    3.54
2.0    3.51
3.0    3.46
4.0    3.49
5.0    3.52
6.0    3.46
7.0    3.48
8.0    3.56
9.0    3.42
Name: customer_rating, dtype: float64